@extends($layout ?? 'layouts.management')
@section('title', 'Inventory Report')
@section('content')
<div class="space-y-6">
    <div><h1 class="text-2xl font-semibold">Inventory Report</h1><p class="mt-1 text-sm text-neutral-500">Current stock is live. Movement history follows the selected date range.</p></div>
    @include('management.reports._filters', ['showChannel' => false])
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">@foreach(['On hand' => $report['summary']['current'], 'Reserved' => $report['summary']['reserved'], 'Available' => $report['summary']['available'], 'Low stock SKUs' => $report['summary']['low_stock'], 'Out-of-stock SKUs' => $report['summary']['out_of_stock']] as $label => $value)<div class="border bg-white p-5"><p class="text-xs uppercase tracking-wider text-neutral-500">{{ $label }}</p><p class="mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
    <section class="overflow-x-auto border bg-white p-6"><h2 class="mb-4 font-semibold">SKU stock</h2><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-neutral-500"><th class="py-3">SKU / product</th><th class="py-3 text-right">On hand</th><th class="py-3 text-right">Reserved</th><th class="py-3 text-right">Available</th></tr></thead><tbody>@forelse($stocks as $sku)<tr class="border-b"><td class="py-3">{{ $sku->sku }} <span class="block text-xs text-neutral-500">{{ $sku->product->name }} · {{ $sku->variant->name }} / {{ $sku->size?->name }}</span></td><td class="py-3 text-right">{{ $sku->stock?->on_hand ?? 0 }}</td><td class="py-3 text-right">{{ $sku->stock?->reserved ?? 0 }}</td><td class="py-3 text-right">{{ $sku->stock?->available ?? 0 }}</td></tr>@empty<tr><td colspan="4" class="py-6 text-center text-neutral-500">No active SKUs.</td></tr>@endforelse</tbody></table><div class="mt-4">{{ $stocks->withQueryString()->links() }}</div></section>
    <section class="overflow-x-auto border bg-white p-6"><h2 class="mb-4 font-semibold">Recent movements in period</h2><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-neutral-500"><th class="py-3">Date</th><th class="py-3">SKU</th><th class="py-3">Type</th><th class="py-3 text-right">Quantity</th><th class="py-3">Reference</th></tr></thead><tbody>@forelse($report['movements'] as $movement)<tr class="border-b"><td class="py-3">{{ $movement->created_at->format('d M Y H:i') }}</td><td class="py-3">{{ $movement->sku?->sku ?? 'Deleted SKU' }}</td><td class="py-3">{{ $movement->type }}</td><td class="py-3 text-right">{{ $movement->quantity }}</td><td class="py-3">{{ $movement->reference }}</td></tr>@empty<tr><td colspan="5" class="py-6 text-center text-neutral-500">No movements in this period.</td></tr>@endforelse</tbody></table></section>
</div>
@endsection
