@extends($layout ?? 'layouts.management')
@section('title', 'Sales Report')
@section('content')
<div class="space-y-6">
    <div><h1 class="text-2xl font-semibold">Sales Report</h1><p class="mt-1 text-sm text-neutral-500">Revenue includes shipping and subtracts discounts. Online uses payment date; POS uses confirmation date.</p></div>
    @include('management.reports._filters')
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">@foreach(['Revenue' => 'Rp '.number_format($sales['revenue'], 0, ',', '.'), 'Online orders' => $sales['orders'], 'Transactions' => $sales['transactions'], 'Units sold' => $sales['units_sold'], 'AOV' => 'Rp '.number_format($sales['aov'], 0, ',', '.')] as $label => $value)<div class="border bg-white p-5"><p class="text-xs uppercase tracking-wider text-neutral-500">{{ $label }}</p><p class="mt-2 text-xl font-semibold">{{ $value }}</p></div>@endforeach</div>
    <section class="overflow-x-auto border bg-white p-6"><h2 class="mb-4 font-semibold">Channel comparison</h2><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-neutral-500"><th class="py-3">Channel</th><th class="py-3 text-right">Revenue</th><th class="py-3 text-right">Transactions</th><th class="py-3 text-right">Units</th></tr></thead><tbody>@foreach(['Online' => $sales['online'], 'POS' => $sales['pos']] as $label => $row)<tr class="border-b"><td class="py-3">{{ $label }}</td><td class="py-3 text-right">Rp {{ number_format($row['revenue'], 0, ',', '.') }}</td><td class="py-3 text-right">{{ $row['transactions'] }}</td><td class="py-3 text-right">{{ $row['units_sold'] }}</td></tr>@endforeach</tbody></table></section>
    <section class="overflow-x-auto border bg-white p-6"><h2 class="mb-4 font-semibold">Daily trend</h2><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-neutral-500"><th class="py-3">Date</th><th class="py-3 text-right">Online</th><th class="py-3 text-right">POS</th><th class="py-3 text-right">Total</th></tr></thead><tbody>@forelse($trend as $day)<tr class="border-b"><td class="py-3">{{ $day['date'] }}</td><td class="py-3 text-right">Rp {{ number_format($day['online'], 0, ',', '.') }}</td><td class="py-3 text-right">Rp {{ number_format($day['pos'], 0, ',', '.') }}</td><td class="py-3 text-right font-medium">Rp {{ number_format($day['total'], 0, ',', '.') }}</td></tr>@empty<tr><td colspan="4" class="py-6 text-center text-neutral-500">No paid sales in this period.</td></tr>@endforelse</tbody></table></section>
</div>
@endsection
