@csrf
@if(isset($voucher)) @method('PUT') @endif
<div class="grid max-w-3xl gap-5 bg-white p-6 sm:grid-cols-2">
    <label class="block text-sm font-medium">Code<input name="code" value="{{ old('code', $voucher->code ?? '') }}" maxlength="50" required class="mt-1 w-full border border-neutral-300 p-3 uppercase"><span class="text-xs text-neutral-500">Letters, numbers, underscore or hyphen.</span>@error('code')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    <label class="block text-sm font-medium">Type<select name="type" required class="mt-1 w-full border border-neutral-300 p-3"><option value="FIXED" @selected(old('type', $voucher->type ?? 'FIXED') === 'FIXED')>Fixed amount (Rp)</option><option value="PERCENTAGE" @selected(old('type', $voucher->type ?? '') === 'PERCENTAGE')>Percentage (%)</option></select>@error('type')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    <label class="block text-sm font-medium">Value<input type="number" name="value" min="1" step="1" value="{{ old('value', $voucher->value ?? '') }}" required class="mt-1 w-full border border-neutral-300 p-3">@error('value')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    <label class="block text-sm font-medium">Minimum purchase (Rp)<input type="number" name="min_purchase" min="0" step="1" value="{{ old('min_purchase', $voucher->min_purchase ?? 0) }}" required class="mt-1 w-full border border-neutral-300 p-3">@error('min_purchase')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    <label class="block text-sm font-medium">Maximum discount (Rp, percentage only)<input type="number" name="max_discount" min="1" step="1" value="{{ old('max_discount', $voucher->max_discount ?? '') }}" class="mt-1 w-full border border-neutral-300 p-3">@error('max_discount')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    <label class="block text-sm font-medium">Total usage limit<input type="number" name="usage_limit" min="1" step="1" value="{{ old('usage_limit', $voucher->usage_limit ?? '') }}" class="mt-1 w-full border border-neutral-300 p-3"><span class="text-xs text-neutral-500">Leave blank for unlimited.</span>@error('usage_limit')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    <label class="block text-sm font-medium">Per-customer limit<input type="number" name="per_user_limit" min="1" step="1" value="{{ old('per_user_limit', $voucher->per_user_limit ?? 1) }}" required class="mt-1 w-full border border-neutral-300 p-3">@error('per_user_limit')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    <div class="sm:col-span-2 grid gap-5 sm:grid-cols-2">
        <label class="block text-sm font-medium">Start date<input type="datetime-local" name="start_date" value="{{ old('start_date', isset($voucher) ? $voucher->start_date?->format('Y-m-d\TH:i') : '') }}" class="mt-1 w-full border border-neutral-300 p-3">@error('start_date')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
        <label class="block text-sm font-medium">End date<input type="datetime-local" name="end_date" value="{{ old('end_date', isset($voucher) ? $voucher->end_date?->format('Y-m-d\TH:i') : '') }}" class="mt-1 w-full border border-neutral-300 p-3">@error('end_date')<span class="block text-xs text-red-700">{{ $message }}</span>@enderror</label>
    </div>
    <label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $voucher->is_active ?? true))> Active</label>
    <div class="sm:col-span-2"><button class="bg-black px-5 py-3 text-xs font-medium uppercase tracking-wider text-white">Save voucher</button></div>
</div>
